import Image from 'next/image';
import {notFound} from 'next/navigation';
import {studies,reels,site} from '@/lib/content';
import {metadata as makeMetadata} from '@/lib/seo';
import {Arrow,Breadcrumbs,ContactBand,JsonLd,Label,PageIntro} from '@/components/ui';
export const dynamicParams=false;
export function generateStaticParams(){return studies.map(s=>({slug:s.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const s=studies.find(s=>s.slug===slug);return s?makeMetadata(`${s.account} — Creator Case Study`,s.summary,`/work/${s.slug}/`,s.index):{}}
export default async function Study({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const s=studies.find(s=>s.slug===slug);if(!s)notFound();return <><article className="gutter"><Breadcrumbs items={[{name:'Work',path:'/work/'},{name:s.account,path:`/work/${s.slug}/`}]}/><PageIntro label={`[ CREATOR_CASE_STUDY / ${s.account.toUpperCase()} ]`} title={s.title} description={s.summary}/><div className="study-meta"><div><Label>ROLE</Label><p>{s.role}</p></div><div><Label>TERRITORY</Label><p>{s.field}</p></div><div><Label>RECORD REVIEWED</Label><time dateTime={site.date}>23 September 2026</time></div></div><JsonLd data={{'@context':'https://schema.org','@type':'CreativeWork',name:`${s.account}: ${s.title}`,description:s.summary,url:site.url+`/work/${s.slug}/`,creator:{'@id':site.url+'/#person','@type':'Person',name:site.name},dateModified:site.date,about:s.field,citation:s.sources.map(x=>x.url)}}/>{s.slug==='sl6dl7'&&<div className="study-hero-media">{reels.slice(0,3).map(r=><Image key={r.id} src={`/media/${r.id}.jpg`} alt={r.alt} width={540} height={960} sizes="(max-width: 700px) 30vw, 25vw"/>)}</div>}<div className="case-sections">{s.sections.map((x,i)=><div key={x.label}><section className="case-section"><Label>{x.label}</Label><div><h2>{x.title}</h2><p>{x.body}</p></div></section>{s.slug==='sl6dl7'&&i===2&&<div className="study-break"><Image src="/media/CytnwFRq0c2.jpg" alt="A person seated with an open book in a reel cover" width={540} height={960} sizes="(max-width: 700px) 100vw, 55vw" loading="lazy"/><div><Label>[ LITERATURE / IN_MOTION ]</Label><p>Words. Image.<br/>A shared feeling.</p></div></div>}</div>)}</div>{s.slug==='sl6dl7'&&<section className="evidence-gallery"><Label>[ THE_ORIGINAL_WORK ]</Label><h2>Follow the reference.</h2><div className="evidence-grid">{reels.map(r=><figure id={r.id} key={r.id}><a href={`https://www.instagram.com/reel/${r.id}/`}><Image src={`/media/${r.id}.jpg`} alt={r.alt} width={540} height={960} sizes="(max-width: 600px) 90vw, 30vw" loading="lazy"/></a><figcaption>{r.title}<a href={`https://www.instagram.com/reel/${r.id}/`}>View original reel <Arrow diagonal/></a></figcaption></figure>)}</div></section>}<section className="source-section"><Label>SOURCES & ATTRIBUTION</Label><ul>{s.sources.map(x=><li key={x.url}><a href={x.url}>{x.label} ↗</a></li>)}</ul><p>Personal creator work. Not a Project Monet client campaign.</p></section><div className="related-work"><Label>CONTINUE EXPLORING</Label><a href="/work/">The work library <Arrow/></a><a href="/expertise/creative-direction/">The creative direction <Arrow/></a></div></article><ContactBand/></>}
