export const site = { name: 'Mayank Harsh', url: 'https://mayankharsh.space', email: 'contact@mayankharsh.space', date: '2026-09-23', instagram: 'https://www.instagram.com/sl6dl7/', secondInstagram: 'https://www.instagram.com/shehzada.says/' };
export const reels = [
 { id:'C093-LuKwqW', title:'Portrait / stillness', category:'Selected reel 01', alt:'Reel cover: close portrait of a person in a white shirt and pearl earring' },
 { id:'CzuANP0K5ML', title:'Stairwell / movement', category:'Selected reel 02', alt:'Reel cover: person descending a dim stairwell' },
 { id:'C3xkNnAoWa_', title:'The night sky', category:'Selected reel 03', alt:'Reel cover: Van Gogh’s Starry Night painting' },
 { id:'CrodTefqiKm', title:'A book / a moment', category:'Selected reel 04', alt:'Reel cover: person in a dark coat holding an open book' },
 { id:'CzpAg5nKgWc', title:'Books in hand', category:'Selected reel 05', alt:'Reel cover: person in a tan coat carrying a stack of books' },
 { id:'CytnwFRq0c2', title:'Walking together', category:'Selected reel 06', alt:'Reel cover: two people walking away in dark clothing' },
];
export type Study = { slug:string; account:string; title:string; summary:string; role:string; field:string; index:boolean; sections:{label:string;title:string;body:string}[]; sources:{label:string;url:string}[] };
export const studies:Study[] = [
 {slug:'sl6dl7',account:'@sl6dl7',title:'A world built around a feeling.',summary:'Poetry, literature and visual storytelling, brought together in a distinctive Instagram identity.',role:'Founder & Creative Director',field:'Poetry / Literature / Dark academia',index:true,sections:[
 {label:'01 / CONTEXT',title:'A home for art, literature and emotion.',body:'@sl6dl7 is Mayank Harsh’s personal creator project on Instagram. Its creative territory brings together poetry, philosophical writing and a dark academia visual language. The account is part of his own creator portfolio.'},
 {label:'02 / INSIGHT',title:'Start with what a person feels.',body:'The creative direction connects a passage of writing with a visual atmosphere. A literary reference becomes an emotional entry point: something a viewer can recognise in their own life. The emphasis is on the relationship between the words, the image and the feeling.'},
 {label:'03 / CONCEPT',title:'Give the account a recognisable world.',body:'Literary references, gothic imagery and introspective themes form a consistent frame for the work. Individual reels can explore different ideas while remaining connected through tone, typography and visual selection.'},
 {label:'04 / EXECUTION',title:'Words, imagery, rhythm.',body:'The published portfolio describes a practice of testing captions, visual themes and reel formats, alongside reviewing Instagram Insights. The selected covers below provide a direct route to the original work. They show how the account packages literature for a short-form feed.'},
 {label:'05 / ROLE',title:'A personal creator practice.',body:'Mayank’s documented role is founder and creative director of @sl6dl7. This case study concerns his creator work. Source artwork, writing and audio retain their respective authorship; creative direction does not imply authorship of every underlying material.'},
 {label:'06 / RESULT & EVIDENCE',title:'The work is the starting point.',body:'The account and the linked reels are the public record of this creative practice. Performance figures change over time, so this edition focuses on the work itself rather than presenting undated counters as current analytics.'},
 {label:'07 / REFLECTION',title:'A consistent emotional language.',body:'Across the selected work, the common thread is a recognisable relationship between literature and feeling. It is a useful lens for understanding the creative direction. It does not, on its own, establish which individual decision caused audience growth.'},
 ],sources:[{label:'Original creator account — @sl6dl7',url:site.instagram},{label:'Founder work attribution — Project Monet',url:'https://www.projectmonet.com/'}]},
 {slug:'shehzada-says',account:'@shehzada.says',title:'Culture, reframed through music.',summary:'A creator project exploring music, Bollywood nostalgia and point-of-view formats.',role:'Founder & format creator',field:'Music / Nostalgia / Social formats',index:false,sections:[
 {label:'01 / CONTEXT',title:'Music as a shared reference.',body:'@shehzada.says is associated with Mayank Harsh’s creator portfolio. The existing portfolio describes work around music, entertainment and nostalgic cultural references.'},
 {label:'02 / CONCEPT',title:'A familiar moment, a new frame.',body:'The documented creative approach uses Bollywood nostalgia, emotional hooks and point-of-view formats. It includes a Shreya Ghoshal series and references to television and film from the 2000s.'},
 {label:'03 / EXECUTION & ROLE',title:'Working with cultural context.',body:'Mayank’s portfolio describes him as the founder and format creator behind the account. It records the use of cultural moments, music releases and competitor research when developing content ideas.'},
 {label:'04 / EVIDENCE',title:'Explore the creator account.',body:'The original account is the reference for this project. This overview describes its documented creative territory; it does not make performance, endorsement or trend-origination claims.'},
 ],sources:[{label:'Original creator account — @shehzada.says',url:site.secondInstagram}]},
];
export const expertise = [
 {slug:'creative-direction',title:'Creative direction',label:'[ CREATIVE_DIRECTION ]',intro:'A coherent point of view across words, imagery and format.',paragraphs:[['Define the emotional territory.','Creative direction starts with the feeling the work should hold. In the @sl6dl7 project, literature and dark academia provide a shared visual and emotional language. The account’s individual pieces belong to a recognisable world.'],['Connect the parts.','A caption, an image and an edit are choices in the same story. Direction gives those choices a relationship: what the viewer sees first, what they read, and what remains when the piece ends.'],['Keep the work recognisable.','A consistent creative identity leaves room for experimentation. Visual themes and formats can change while the underlying tone remains clear. The selected work shows this approach through a personal creator project.']],study:'sl6dl7'},
 {slug:'social-media-strategy',title:'Social media strategy',label:'[ AUDIENCE_INSIGHT ]',intro:'Connect the account’s purpose to the way people encounter its work.',paragraphs:[['Start with the audience.','The public portfolio describes a research-led process: understand the audience, study related accounts, define a creative territory, and choose a small set of content themes. These decisions give the publishing process a direction.'],['Develop formats, then review them.','Hooks, captions and visual themes can be varied and compared. Instagram Insights supports that review. The aim is to understand audience response in context instead of treating one unusually successful post as a repeatable promise.'],['Build continuity.','The creator work spans poetry, literature and music. A clear profile, recognisable formats and an editorial rhythm give people a reason to return. This portfolio documents the creative practice; agency engagements are handled through Project Monet.']],study:'sl6dl7'},
];
export const nav = [{href:'/work/',label:'Work'},{href:'/about/',label:'About'},{href:'/expertise/creative-direction/',label:'Expertise'}];
